name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

permissions:
  contents: read

jobs:
  cd:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: upload app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no shani@20.234.206.76 <<EOF
          
          echo ''
          echo '---starting update app code---'
          if [ -d sum-http-client ]; then 
              cd sum-http-client
              git pull origin main
          else
              git clone https://github.com/shaniblau/sum-http-client.git
              cd sum-http-client
          fi
          
          echo ''
          echo '---starting dependencies installment----'
          find ./ -type f -name "*.sh" -exec chmod +x {} \; -exec sudo mv -v {} /usr/bin/ \;
          //usr/bin/install_dependencies.sh
          pip install -r dependencies/requirements.txt

          echo ''
          echo '----starting all services----'
          find ./deployment/ -type f -name "*.service" -exec sudo mv -v {} /etc/systemd/system/ \;
          sudo systemctl enable http_client
          sudo systemctl restart http_client

          echo ''
          echo '----starting crontabs----'
          (crontab -l ; echo "* * * * * expire_files.sh /home/shani/images/") | crontab -

          EOF