name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

permissions:
  contents: read

jobs:
  cd:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: update app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no shani@20.234.206.76 <<EOF
          
          echo ''
          echo '----updating app----'
          cd sum-http-client
          git pull origin main
          
          echo ''
          echo '----restarting all services----'
          sudo systemctl restart http_client

          EOF